version: 2
environment:
  name: CI
updates:
  - package-ecosystem: "bundler"
    directory: "/api"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10

  - package-ecosystem: "bundler"
    directory: "/web"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
