services:
  db:
    image: postgres:16
    container_name: nova_lance_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: nova_lance_development
      TZ: "Asia/Tokyo"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - nova_lance_network

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: nova_lance_api
    command: >
      bash -c "
        wait-for-it.sh db:5432 -t 60 -- echo 'PostgreSQL is up - executing command' &&
        bundle config --local path /usr/local/bundle &&
        bundle check || bundle install &&
        rm -f tmp/pids/server.pid &&
        bundle exec rails db:prepare &&
        bundle exec puma -C config/puma.rb
      "
    volumes:
      - ./api:/rails_api
      # - bundle_cache:/usr/local/bundle
    ports:
      - "3001:3001"
    environment:
      BUNDLE_WITHOUT: ""
      RAILS_ENV: development
      RAILS_LOG_TO_STDOUT: true
      DATABASE_HOST: db
      DATABASE_USER: postgres
      DATABASE_PASSWORD: password
      DATABASE_NAME: nova_lance_development
    depends_on:
      - db
    networks:
      - nova_lance_network
    stdin_open: true
    tty: true

  web:
    build:
      context: ./web
      dockerfile: Dockerfile
    container_name: nova_lance_web
    command: >
      bash -c "
        rm -f /rails_web/.bundle/config &&
        rm -rf /rails_web/tmp/cache/assets
        export BUNDLE_PATH=/usr/local/bundle &&
        bundle config --global path /usr/local/bundle &&
        bundle config --global without development:test &&
        bundle config --global deployment false &&
        echo '--- Running bundle check ---' &&
        bundle check &&
        echo '--- Bundle check passed. Starting application... ---' &&
        rm -f tmp/pids/server.pid &&
        bin/dev
      "
    volumes:
      - ./web:/rails_web
      - /rails_web/node_modules
      # - bundle_cache:/usr/local/bundle
    ports:
      - "3000:3000"
    environment:
      BUNDLE_WITHOUT: "development:test"
      RAILS_ENV: development
      RAILS_LOG_TO_STDOUT: true
    networks:
      - nova_lance_network
    stdin_open: true
    tty: true

volumes:
  postgres_data:
  # bundle_cache:

networks:
  nova_lance_network:
    driver: bridge
