plugins:
  - rubocop-rails
  - rubocop-performance
  - rubocop-rspec

# .rubocop.yml
# plugins:
#   - rubocop-rails

# Omakase Ruby styling for Rails
# inherit_gem: { rubocop-rails-omakase: rubocop.yml }

# Overwrite or add rules to create your own house style
#
# # Use `[a, [b, c]]` not `[ a, [ b, c ] ]`
# Layout/SpaceInsideArrayLiteralBrackets:
#   Enabled: false

Layout/SpaceAroundOperators:
  Enabled: true

Layout/SpaceInsideReferenceBrackets:
  Enabled: true
