name: Build API

on:
  pull_request:
  push:
    branches: [main]

jobs:
  scan_ruby:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Ruby and cache gems for API
        uses: ruby/setup-ruby@v1
        with:
          working-directory: ./api
          bundler-cache: true

      - name: Scan for common Rails security vulnerabilities using static analysis
        working-directory: ./api
        run: bin/brakeman --no-pager

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Ruby and cache gems for API
        uses: ruby/setup-ruby@v1
        with:
          working-directory: ./api
          bundler-cache: true

      - name: Lint code for consistent style
        working-directory: ./api
        run: bin/rubocop -f github

  test:
    runs-on: ubuntu-latest
    environment:
      name: CI
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
        ports:
          - 5432:5432
        options: --health-cmd="pg_isready" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - name: Install system packages
        run: sudo apt-get update && sudo apt-get install --no-install-recommends -y libpq-dev

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Ruby and cache gems for API
        uses: ruby/setup-ruby@v1
        with:
          working-directory: ./api
          bundler-cache: true

      - name: Run tests
        working-directory: ./api
        env:
          RAILS_ENV: test
          DATABASE_URL: postgres://postgres:${{ secrets.POSTGRES_PASSWORD }}@localhost:5432/nova_lance_test
        run: |
          bundle exec rails db:prepare
          bundle exec rails spec
