name: Build WEB

on:
  pull_request:
  push:
    branches: [main]

jobs:
  scan_web_security:
    name: Scan WEB for security (Brakeman)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Ruby and cache gems for WEB
        uses: ruby/setup-ruby@v1
        with:
          working-directory: ./web
          bundler-cache: true

      - name: Scan WEB for security vulnerabilities
        working-directory: ./web
        run: bin/brakeman --no-pager

  lint_web:
    name: Lint WEB (RuboCop)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Ruby and cache gems for WEB
        uses: ruby/setup-ruby@v1
        with:
          working-directory: ./web
          bundler-cache: true

      - name: Lint WEB code for style
        working-directory: ./web
        run: bin/rubocop -f github
