name: Build API

on:
  pull_request:
  push:
    branches: [main]

jobs:
  scan_ruby:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "api/.ruby-version"

      - name: Install API dependencies
        working-directory: ./api
        run: bundle install --jobs 4 --retry 3

      - name: Scan for common Rails security vulnerabilities using static analysis
        working-directory: ./api
        run: bin/brakeman --no-pager

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "api/.ruby-version"

      - name: Install API dependencies
        working-directory: ./api
        run: bundle install --jobs 4 --retry 3

      - name: Lint code for consistent style
        working-directory: ./api
        run: bin/rubocop -f github

  test:
    runs-on: ubuntu-latest
    environment:
      name: CI
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
        ports:
          - 5432:5432
        options: --health-cmd="pg_isready" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - name: Install system packages
        run: sudo apt-get update && sudo apt-get install --no-install-recommends -y libpq-dev # pg gem のために必要

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Ruby and cache gems for API
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: .ruby-version
          working-directory: ./api
          bundler-cache: true

      # 上記の bundler-cache: true でうまくいかない場合や、より明示的にしたい場合は、
      # ruby/setup-ruby から bundler-cache: true と working-directory: ./api を削除し、
      # 以下のステップを代わりに追加します。
      # - name: Set up Ruby
      #   uses: ruby/setup-ruby@v1
      #   with:
      #     ruby-version-file: 'api/.ruby-version'
      # - name: Install API dependencies
      #   working-directory: ./api
      #   run: bundle install --jobs 4 --retry 3

      - name: Run tests
        working-directory: ./api
        env:
          RAILS_ENV: test
          DATABASE_URL: postgres://postgres:${{ secrets.POSTGRES_PASSWORD }}@localhost:5432/nova_lance_test
        run: |
          bundle exec rails db:prepare
          bundle exec rails test
